In [ ]:
import numpy as np

Creating a Matrix using numpy

In [ ]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2=np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:
matrix_2.shape

(3, 3)

Creating matrices with random values

In [ ]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.60257248 0.25990403 0.51707809]
 [0.42665792 0.08712885 0.04151462]
 [0.49850429 0.93875732 0.47766975]]


In [ ]:
# creatiing matrix with random integers
random_integer_matrix=np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[36 49 59 84 68]
 [95 97 46 37  1]
 [ 2 40  5 56 69]
 [66 79 95 70 65]]


Matrix with all the values as 1

In [ ]:
matrix_3=np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3=np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null matrix or zero matrix

In [ ]:
null_matrix=np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity Matrix

In [ ]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [ ]:
# creatiing matrix with random integers
a=np.random.randint(100,size=(4,5))
print(a)

[[53 63 80  5 31]
 [70 81  7  0 23]
 [24 59 33 39 77]
 [81 95 84 93 44]]


In [ ]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[53 70 24 81]
 [63 81 59 95]
 [80  7 33 84]
 [ 5  0 39 93]
 [31 23 77 44]]


Matrix addiction

Two matrices can be added only if they have the same shape.

In [ ]:
# creating two two matrices

A=np.array([[2,3],[4,5]])
B=np.array([[6,7],[8,9]])

In [ ]:
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


Adding two matrices

In [ ]:
sum=A+B

In [ ]:
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# create two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [ ]:
print(matrix_1)
print(matrix_2)

[[3 3 3]
 [1 3 4]
 [9 0 0]]
[[17  7  5]
 [11  5 18]
 [16  5  1]]


In [ ]:
sum=np.add(matrix_1,matrix_2)

In [ ]:
print(sum)

[[20 10  8]
 [12  8 22]
 [25  5  1]]


Matrix subraction

In [ ]:
#createing two matrices
A=np.array([[2,3],[4,5]])
B=np.array([[6,7],[8,9]])

In [ ]:
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [ ]:
difference=A-B

In [ ]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [ ]:
#create two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [ ]:
print(matrix_1)
print(matrix_2)

[[7 7 9]
 [9 3 0]
 [0 9 7]]
[[ 6 13 13]
 [17 15 18]
 [ 0 14  9]]


In [ ]:
diff=np.subtract(matrix_1,matrix_2)

In [ ]:
print(diff)

[[  1  -6  -4]
 [ -8 -12 -18]
 [  0  -5  -2]]


Multiplying a matrix by a scalar

In [ ]:
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[9 1 5 9]
 [8 6 3 1]
 [7 0 3 2]
 [1 3 0 8]]


In [ ]:
product=np.multiply(x,y)

In [ ]:
print(product)

[[45  5 25 45]
 [40 30 15  5]
 [35  0 15 10]
 [ 5 15  0 40]]


**Multiplying 2 matrices**

In [ ]:
#create two matrices with random values
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,4))

In [ ]:
print(matrix_3)
print(matrix_4)

[[1 3 1]
 [1 3 1]
 [4 2 1]]
[[4 1 4 4]
 [2 3 1 4]
 [3 1 4 2]]


In [ ]:
product=np.dot(matrix_3,matrix_4)

In [ ]:
print(product)

[[13 11 11 18]
 [13 11 11 18]
 [23 11 22 26]]


**Element wise matrix multiplication**

In element wise multiply both matrices should have equal no of rows and columns

In [ ]:
# create two matrices with random values
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,3))

In [ ]:
print(matrix_3)
print(matrix_4)

[[3 1 0]
 [2 0 0]
 [3 4 0]]
[[1 2 1]
 [3 0 3]
 [4 2 1]]


In [ ]:
product=np.multiply(matrix_3,matrix_4)

In [ ]:
print(product)

[[ 3  2  0]
 [ 6  0  0]
 [12  8  0]]
