<a href="https://colab.research.google.com/github/Shreyachodhary/Machine-Learning/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy-Numerical Python

Advantages of NumPy Arrays:
1.Allows several Mathematical Operations
2.Faster operations

In [6]:
import numpy as np

List vs NumPy-Time Taken

In [3]:
from time import process_time  # process_time is used to measure the time repeat for a particular process

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0007658839999997724


In [5]:
np_array = np.array([i for i in range (10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.0012195280000000253


NumPy Arrays

In [1]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [13]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix, identity matric has same no of rows and columns
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.41821168 0.74647875 0.97939728 0.64358165]
 [0.0536489  0.20078857 0.26429693 0.14847412]
 [0.31056518 0.80104957 0.21738142 0.01890068]]


In [18]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[55 26 32 54 84]
 [99 46 62 76 96]
 [86 61 36 85 13]]


In [19]:
# array of evenly spaced values-->specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [20]:
# array of evenly spaced values--> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [21]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [22]:
c = np.random.randint(10,90,(5,5))
print(c)

[[59 85 28 32 43]
 [11 16 20 86 75]
 [66 55 55 35 76]
 [80 40 50 18 26]
 [20 88 81 48 12]]


In [23]:
# array dimension
print(c.shape)

(5, 5)


In [24]:
# number of dimensions
print(c.ndim)

2


In [25]:
# number of elements in a array
print(c.size)

25


In [26]:
# checking the data type of the values in the array
print(c.dtype)     #64 bit integer values

int64


Mathematical operations on anp array

In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[3 4 2]
 [5 6 7]
 [0 0 0]]
[[15 18 18]
 [19 16 15]
 [12 10 18]]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 22 20]
 [24 22 22]
 [12 10 18]]
[[-12 -14 -16]
 [-14 -10  -8]
 [-12 -10 -18]]
[[ 45  72  36]
 [ 95  96 105]
 [  0   0   0]]
[[0.2        0.22222222 0.11111111]
 [0.26315789 0.375      0.46666667]
 [0.         0.         0.        ]]


In [34]:
print(np.add(a,b))

[[18 22 20]
 [24 22 22]
 [12 10 18]]


In [35]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[-12 -14 -16]
 [-14 -10  -8]
 [-12 -10 -18]]
[[ 45  72  36]
 [ 95  96 105]
 [  0   0   0]]
[[0.2        0.22222222 0.11111111]
 [0.26315789 0.375      0.46666667]
 [0.         0.         0.        ]]


Array Manipulation

In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 5 1]
 [6 2 7]]
(2, 3)


In [37]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 6]
 [5 2]
 [1 7]]
(3, 2)


In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 2 0]
 [8 7 9]]
(2, 3)


In [39]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 8]
 [2 7]
 [0 9]]
(3, 2)


In [40]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 4 0]
 [1 3 1]]
(2, 3)


In [41]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 4]
 [0 1]
 [3 1]]
(3, 2)
