<a href="https://colab.research.google.com/github/Shreyachodhary/Machine-Learning/blob/main/Pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# Create dataframes
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [ ]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

Indexing

columnname,rowindex[loc],rowindex columnindex number[.iloc]

In [ ]:
# column indexing
df['Column1']
type(df['Column1'])

pandas.core.series.Series

In [ ]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [ ]:
#using row index name loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [ ]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [ ]:
df.iloc[2:5,1:4]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
df.iloc[0:5,0::3]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [ ]:
#convert dataframes into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
# Basic operations
df.isnull().sum()   ## a quick way to see how many missing values eacch column has

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=["Column1","Column2","Column3"])

In [ ]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [ ]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [ ]:
df['Column3'].value_counts()

Column3
2    1
4    1
Name: count, dtype: int64

In [ ]:
df['Column2'].unique()

array([nan,  3.])

In [ ]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df['Column2'].unique()

array([ 1,  5,  9, 13, 17])

In [ ]:
df>2

Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True

In [ ]:
df['Column2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Name: Column2, dtype: bool

In [ ]:
df[df['Column2']>2]  #  returns a new DataFrame with only the rows where 'Column2' has values greater than 2. It’s commonly used for filtering data based on conditions.

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

**Reading diffeent data sources with the help of pandas**

->When a csv file is read it is converted into data frames.This is done using **read_csv*

->**StringIO** is a class in the io module that lets you treat a string like a file object.For eg: If we have a csv data as a string it will convert string into a file like object then we read the data using** pd.read_csv()**

->**in-memory file format** it means you’re working with file-like data stored in memory (RAM) instead of saving or reading it from a physical file on disk.





In [ ]:
from io import StringIO

In [ ]:
url="https://raw.githubusercontent.com/krishnaik06/Tutorials-Python-In-Hindi/main/mercedesbenz.csv"
df=pd.read_csv(url)
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
data=('col1,col2,col3\n'
'x,y,1\n'
'a,b,2\n'
'c,d,3')

In [ ]:
type(data)

str

In [ ]:
# in-memory file object
StringIO(data)

In [ ]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
# usecols parameter is used to read only specific columns from a CSV file.
url="https://raw.githubusercontent.com/krishnaik06/Tutorials-Python-In-Hindi/main/mercedesbenz.csv"
df=pd.read_csv(url,usecols=['X0','X1','X2','X3','X4','X5'])
df.head()

X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [ ]:
# to convert data back into csv file
df.to_csv('test.csv', index=False)  # index=False remove index from the file

In [ ]:
## datatypes in csv
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11')

In [ ]:
df=pd.read_csv(StringIO(data))

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      int64  
 2   c       3 non-null      int64  
 3   d       2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 228.0 bytes


In [ ]:
df=pd.read_csv(StringIO(data),dtype='object')   # with dtype we can have desired datatype bydefault

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes


In above data Column d is of type float64 because it contains at least one missing value (NaN). Here's why that matters:

In pandas, missing values (NaN) are represented as float by default.

So, even if the other values in column d are integers, the presence of a NaN forces pandas to convert the entire column to float64 to accommodate it.

In [ ]:
df.head()

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [ ]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [ ]:
df['a'][0]  # to find desired element

'1'

In [ ]:
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      float64
 2   c       3 non-null      int64  
 3   d       2 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 228.0 bytes


In [ ]:
df.dtypes  # to check the data types

a      int64
b    float64
c      int64
d    float64
dtype: object

In [ ]:
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [ ]:
pd.read_csv(StringIO(data),index_col=0)  # index_col=0 tells pandas to use the first column (column at position 0) as the index of the DataFrame.

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [ ]:
# use index cols and usecols
data = ('a,b,c\n'
        '4,apple,bat\n'
        '8,orange,cow')

In [ ]:
pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col=0)

b    c
a             
4   apple  bat
8  orange  cow

In [ ]:
pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')
# the above url is of a tab seperated file we can read a tab seperated file using read_csv() by using sep='\t' parameter

HTTPError: HTTP Error 403: Forbidden

In this part we wre going to learn about

1.   read Json(read_json)
2.   To Json(to_json)
3.   Json Normalize



In [ ]:
data = '{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr.Developer"}]}'

In [ ]:
type(data)

str

In [ ]:
pd.read_json(data)

<ipython-input-5-f47fb7e58c56>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr.Developer'}

In [ ]:
pd.read_json(data,orient='records')  #orient='records' tells pandas how the JSON is structured — in this case, it's a list of records (dictionaries). orient='column' also give the same output

<ipython-input-6-14a1967e27cb>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='records')


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr.Developer'}

In [ ]:
pd.read_json(data,orient='index')

<ipython-input-7-9d3e30169c67>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='index')


0
employee_name                                              James
email                                            james@gmail.com
job_profile    [{'title1': 'Team Lead', 'title2': 'Sr.Develop...

In [ ]:
pd.read_json(data,orient='split')
#we cannot use spit with this format of json
#Format for orient='split'
#It should be a dictionary with 3 specific keys:

#"columns" → a list of column names

#"index" → a list of row indices

#"data" → a 2D list of values (rows)
#eg:{
  "columns": ["name", "age"],
  "index": [0, 1, 2],
  "data": [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 28]
  ]
}



<ipython-input-8-d7d651528374>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='split')


ValueError: JSON data had unexpected key(s): email, employee_name, job_profile

In [ ]:
import pandas as pd
df=pd.DataFrame([['a','b'],['c','d']],
                index=['row 1','row 2'],
                columns=['col 1','col 2'])


In [ ]:
df

col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json()  # convert the object into json string

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [ ]:
df.to_json(orient='columns')

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [ ]:
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [ ]:
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [ ]:
schema='{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [ ]:
pd.read_json(schema,orient='table')

<ipython-input-25-964d637db6ca>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(schema,orient='table')


col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

In [ ]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [ ]:
df.to_json(orient='index')

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [ ]:
data=[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr.Developer"}}]

In [ ]:
pd.read_json(data)

<ipython-input-30-f47fb7e58c56>:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr.Developer'}

In [ ]:
pd.json_normalize(data)  # normalize semi-structured JSON data into a flat table ,semi-structured because have nested key value pairs

employee_name            email job_profile.title1 job_profile.title2
0         James  james@gmail.com          Team Lead       Sr.Developer

In [ ]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]


In [ ]:
pd.json_normalize(data)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [ ]:
pd.json_normalize(data,max_level=0) # max_level=0 means we have to go only upto one level of nested dictionary

id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mark Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [ ]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [ ]:
pd.json_normalize(data)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor  
0    Rick Scott  
1   John Kasich

In [ ]:
pd.json_normalize(data, "counties",["state", "shortname",["info",'governor']])

name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich