NumPy-Numerical Python

Advantages of NumPy Arrays:
1.Allows several Mathematical Operations
2.Faster operations

In [1]:
import numpy as np

List vs NumPy-Time Taken

In [2]:
from time import process_time  # process_time is used to measure the time repeat for a particular process

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0012354900000000058


In [4]:
np_array = np.array([i for i in range (10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.0004927509999999025


NumPy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [12]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix, identity matric has same no of rows and columns
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.80635101 0.14940791 0.40749272 0.85068749]
 [0.92339871 0.26572633 0.98795814 0.55871407]
 [0.06254152 0.80197894 0.20677156 0.74901537]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[23 86 89 62 36]
 [74 50 37 97 42]
 [81 69 89 29 86]]


In [18]:
# array of evenly spaced values-->specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [19]:
# array of evenly spaced values--> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[39 76 43 32 10]
 [25 74 46 39 51]
 [72 82 22 88 77]
 [39 41 44 55 52]
 [60 24 26 75 43]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in a array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)     #64 bit integer values

int64


Mathematical operations on anp array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[7 8 6]
 [5 8 7]
 [0 7 4]]
[[16 14 16]
 [15 19 14]
 [10 12 12]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 22 22]
 [20 27 21]
 [10 19 16]]
[[ -9  -6 -10]
 [-10 -11  -7]
 [-10  -5  -8]]
[[112 112  96]
 [ 75 152  98]
 [  0  84  48]]
[[0.4375     0.57142857 0.375     ]
 [0.33333333 0.42105263 0.5       ]
 [0.         0.58333333 0.33333333]]


In [30]:
print(np.add(a,b))

[[23 22 22]
 [20 27 21]
 [10 19 16]]


In [31]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[ -9  -6 -10]
 [-10 -11  -7]
 [-10  -5  -8]]
[[112 112  96]
 [ 75 152  98]
 [  0  84  48]]
[[0.4375     0.57142857 0.375     ]
 [0.33333333 0.42105263 0.5       ]
 [0.         0.58333333 0.33333333]]


Array Manipulation

In [32]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 8 1]
 [6 4 4]]
(2, 3)


In [33]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 6]
 [8 4]
 [1 4]]
(3, 2)


In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 8 4]
 [5 7 9]]
(2, 3)


In [35]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 5]
 [8 7]
 [4 9]]
(3, 2)


In [36]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 4 6]
 [6 5 6]]
(2, 3)


In [37]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 4]
 [6 6]
 [5 6]]
(3, 2)
